//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDTelefoniaEntities : DbContext
    {
        public BDTelefoniaEntities()
            : base("name=BDTelefoniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Departamento> tbl_Departamento { get; set; }
        public virtual DbSet<tbl_Municipio> tbl_Municipio { get; set; }
    
        public virtual int sp_UpdateDepartamentos(Nullable<int> codigo, string nombre, Nullable<int> codigoAuxiliar)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoAuxiliarParameter = codigoAuxiliar.HasValue ?
                new ObjectParameter("codigoAuxiliar", codigoAuxiliar) :
                new ObjectParameter("codigoAuxiliar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateDepartamentos", codigoParameter, nombreParameter, codigoAuxiliarParameter);
        }
    }
}
