//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Municipio
    {
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int CodigoDepartamento { get; set; }
        public int Indicativo { get; set; }
        public int Id { get; set; }
    
        public virtual tbl_Departamento tbl_Departamento { get; set; }
    }
}
